// <auto-generated />
using System;
using DataAccessLayer_BankManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer_BankManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer_BankManagementSystem.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountBalance = 1500.50m,
                            AccountNumber = "ACC10001",
                            ClientName = "John Smith",
                            Phone = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            AccountBalance = 2500.75m,
                            AccountNumber = "ACC10002",
                            ClientName = "Emily Johnson",
                            Phone = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            AccountBalance = 3200.00m,
                            AccountNumber = "ACC10003",
                            ClientName = "Michael Brown",
                            Phone = "555-0103"
                        },
                        new
                        {
                            Id = 4,
                            AccountBalance = 500.25m,
                            AccountNumber = "ACC10004",
                            ClientName = "Sarah Davis",
                            Phone = "555-0104"
                        },
                        new
                        {
                            Id = 5,
                            AccountBalance = 7500.00m,
                            AccountNumber = "ACC10005",
                            ClientName = "David Wilson",
                            Phone = "555-0105"
                        },
                        new
                        {
                            Id = 6,
                            AccountBalance = 1200.00m,
                            AccountNumber = "ACC10006",
                            ClientName = "Jennifer Martinez",
                            Phone = "555-0106"
                        },
                        new
                        {
                            Id = 7,
                            AccountBalance = 450.50m,
                            AccountNumber = "ACC10007",
                            ClientName = "Robert Taylor",
                            Phone = "555-0107"
                        },
                        new
                        {
                            Id = 8,
                            AccountBalance = 6800.25m,
                            AccountNumber = "ACC10008",
                            ClientName = "Lisa Anderson",
                            Phone = "555-0108"
                        },
                        new
                        {
                            Id = 9,
                            AccountBalance = 950.00m,
                            AccountNumber = "ACC10009",
                            ClientName = "Thomas Thomas",
                            Phone = "555-0109"
                        },
                        new
                        {
                            Id = 10,
                            AccountBalance = 3500.75m,
                            AccountNumber = "ACC10010",
                            ClientName = "Amanda Garcia",
                            Phone = "555-0110"
                        });
                });

            modelBuilder.Entity("DataAccessLayer_BankManagementSystem.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasMaxLength(255)
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenRevokedAt")
                        .HasMaxLength(255)
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Mohammadshiplak@gmail.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Admin",
                            UserName = "Mohammad_Shiplak"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Teller",
                            UserName = "jane_smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mike@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Client",
                            UserName = "mike_jones"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sara@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Client",
                            UserName = "sara_wilson"
                        },
                        new
                        {
                            Id = 5,
                            Email = "david@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Client",
                            UserName = "david_brown"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emily@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Teller",
                            UserName = "emily_davis"
                        },
                        new
                        {
                            Id = 7,
                            Email = "robert@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Client",
                            UserName = "robert_taylor"
                        },
                        new
                        {
                            Id = 8,
                            Email = "lisa@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Client",
                            UserName = "lisa_miller"
                        },
                        new
                        {
                            Id = 9,
                            Email = "thomas@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Client",
                            UserName = "thomas_wilson"
                        },
                        new
                        {
                            Id = 10,
                            Email = "amy@example.com",
                            PasswordHash = "$2a$11$h8pAqCpqQKjF1GK9QKKvR.e7iZPmNkRdFLLNz7FGC0l7KTSZFvxrq",
                            Role = "Client",
                            UserName = "amy_jackson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
